server:
  port: 80
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: test
    password: 1234
  jpa:
    show-sql: true
    database: oracle
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
#  redis:
#    host: localhost
#    port: 6379